project:
  type: website
  output-dir: docs
website:
  title: "HydroSimul"
  favicon: "Kan.svg"
  page-navigation: true   
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Dataset"
        href: dataset/index.qmd
      - text: "Dataprocess"
        href: dataprocess/index.qmd
        
  
  sidebar:
    - id: dataset
      collapse-level: 1
      contents:
        - TEXT: "Overview"
          href: dataset/index.qmd
        - dataset/meteo.qmd      
        - dataset/hydro.qmd      
        - dataset/geoph.qmd      
    - id: dataprocess
      collapse-level: 1
      contents:
        - section: "Dataprocess"
          href: dataprocess/index.qmd
          contents: 
            - section: "Data Format"
              contents:
                - dataprocess/basic_format.qmd      
                - dataprocess/NetCDF.qmd      
                - dataprocess/spatial_data.qmd      
            - section: "Processing with Skript"
              contents:
                - dataprocess/basic_r_python.qmd      


format:
  html:
    theme: 
    - lux
    - RUB.scss
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 400px
      gutter-width: 1.5rem    


execute:
  freeze: auto