project:
  type: website

website:
  title: "HydroSimul"
  favicon: "Kan.svg"
  page-navigation: true   
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Dataset"
        href: dataset/index.qmd
      - text: "Dataprocess"
        href: dataprocess/index.qmd
        
  
  sidebar:
    - id: dataset
      collapse-level: 1
      contents:
        - TEXT: "Overview"
          href: dataset/index.qmd
        - dataset/meteo.qmd      
        - dataset/hydro.qmd      
        - dataset/geoph.qmd      
    - id: dataprocess
      collapse-level: 1
      contents:
        - section: "Overview"
          href: dataprocess/index.qmd
        - section: "Data Manipulate"
          contents:
            - dataprocess/basic_format.qmd      
            - dataprocess/NetCDF.qmd      
            - dataprocess/spatial_data.qmd      


format:
  html:
    theme: 
    - lux
    - RUB.scss
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 400px
      gutter-width: 1.5rem    


execute:
  freeze: auto