project:
  type: website

website:
  title: "HS_Data"
  favicon: "Kan.svg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
    - lux
    - RUB.scss
    toc: true

editor: visual

execute:
  freeze: auto