project:
  type: website
  output-dir: docs
website:
  title: "HydroSimul"
  favicon: "Kan.svg"
  page-navigation: true   
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Dataprocess"
        href: dataprocess/index.qmd
      - text: "Modelling"
        href: modelling/index.qmd
        
  
  sidebar:
    - id: dataprocess
      collapse-level: 1
      contents:
        - section: "Dataprocess"
          href: dataprocess/index.qmd
          contents: 
            - dataprocess/basic_r_python.qmd      
            - section: "Data-Processing"
              contents:
                - dataprocess/basic_format.qmd      
                - dataprocess/data_load.qmd      
                - dataprocess/NetCDF.qmd      
            - section: "Spatial Data"
              contents:
                - dataprocess/spatial_data.qmd      
                - dataprocess/extract_spatial.qmd
            - section: "Timeserises"
              contents:
                - dataprocess/timeserises_process.qmd      
                - dataprocess/timeserises_visual.qmd      
                - dataprocess/timeserises_analyse.qmd      
            - section: "Statistic"
              contents:
                - dataprocess/statistic_basic.qmd      
                - dataprocess/statistic_graphic.qmd      
            - section: "Visualization"
              contents:
                - dataprocess/visual_plotElements.qmd      
                - dataprocess/visual_ggplot2Basic.qmd      
                
    - id: modelling
      collapse-level: 1
      contents:
        - section: "Modelling"
          href: modelling/index.qmd
          contents: 
            - modelling/basic_concept.qmd      
            - modelling/model_linearReservoir.qmd      
            - modelling/model_caliLinearReser.qmd      


format:
  html:
    theme: 
    - lux
    - RUB.scss
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 400px
      gutter-width: 1.5rem    


execute:
  freeze: auto