classes: {
        bxR: {
        style: {
            stroke: "#65b32e"
            fill: "#f4ffe3"
        }
    }
    bxPy: {
        style: {
            stroke: "#ef7d00"
            fill: "#fff8e1"
        }
    }
    bxGSW: {
        style: {
            stroke: "#e0318a"
            fill: "#fff3ff"
        }
    }
    bxING: {
        style: {
            stroke: "#00a1d9"
            fill: "#deffff"
        }
    }
}